spring.application.name=cloud-storage
spring.datasource.username=postgres
spring.datasource.password=Jambo278
spring.datasource.url=jdbc:postgresql://localhost:5433/cloud_storage
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.example.cloudstorage = INFO
